package main;

public class LayoutResources
{
	public static final String DEFAULT_TAG_OPENING_DECLARATOR = "<";
	public static final String DEFAULT_TAG_CLOSER_DECLARATOR = ">";
	
	public static final String DEFAULT_UNIQUE_TAG_OPENING_DECLARATOR = "";
	public static final String DEFAULT_UNIQUE_TAG_CLOSING_DECLARATOR = "/";
	public static final String DEFAULT_FULL_UNIQUE_TAG_OPENING_SEQUENCE = DEFAULT_TAG_OPENING_DECLARATOR + DEFAULT_UNIQUE_TAG_OPENING_DECLARATOR;
	public static final String DEFAULT_FULL_UNIQUE_TAG_CLOSING_SEQUENCE = DEFAULT_UNIQUE_TAG_CLOSING_DECLARATOR + DEFAULT_TAG_CLOSER_DECLARATOR;
	
	public static final String DEFAULT_GROUP_TAG_OPENING_DECLARATOR = "";
	public static final String DEFAULT_GROUP_TAG_CLOSING_DECLARATOR = "";
	public static final String DEFAULT_FULL_GROUP_TAG_OPENING_SEQUENCE = DEFAULT_TAG_OPENING_DECLARATOR + DEFAULT_GROUP_TAG_OPENING_DECLARATOR;
	public static final String DEFAULT_FULL_GROUP_TAG_CLOSING_SEQUENCE = DEFAULT_GROUP_TAG_CLOSING_DECLARATOR + DEFAULT_TAG_CLOSER_DECLARATOR;
	
	public static final String DEFAULT_TAG_CLOSER_OPENING_DECLARATOR = "/";
	public static final String DEFAULT_TAG_CLOSER_CLOSING_DECLARATOR = "";
	public static final String DEFAULT_FULL_TAG_CLOSER_OPENING_SEQUENCE = DEFAULT_TAG_OPENING_DECLARATOR + DEFAULT_TAG_CLOSER_OPENING_DECLARATOR;
	public static final String DEFAULT_FULL_TAG_CLOSER_CLOSING_SEQUENCE = DEFAULT_TAG_CLOSER_CLOSING_DECLARATOR + DEFAULT_TAG_CLOSER_DECLARATOR;

	public static final String DEFAULT_META_TAG_OPENING_DECLARATOR = "!";
	public static final String DEFAULT_META_TAG_CLOSING_DECLARATOR = "";
	public static final String DEFAULT_FULL_META_TAG_OPENING_SEQUENCE = DEFAULT_TAG_OPENING_DECLARATOR + DEFAULT_META_TAG_OPENING_DECLARATOR;
	public static final String DEFAULT_FULL_META_TAG_CLOSING_SEQUENCE = DEFAULT_META_TAG_CLOSING_DECLARATOR + DEFAULT_TAG_CLOSER_DECLARATOR;
	
	
	
	public static final String DEFAULT_PROPERTY_VALUE_ASSIGNMENT_SEQUENCE = "=";
	
	public LayoutResources()
	{
		
	}
}
